# Generated by Django 5.2.7 on 2025-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField()),
                ('rg', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField()),
                ('endereco', models.CharField()),
                ('data_nascimento', models.DateTimeField()),
                ('sexo', models.CharField()),
                ('ativo', models.CharField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
